### ISSUE TITLE
module compiled with Swift 5.3 cannot be imported by the Swift 5.3.1

### ISSUE THREAD

**Issue by MatthewCallery** [rockbruno/danger-SwiftInfo#4]
I'm getting the following error when running danger-SwiftInfo on CircleCI.

The app is compiled using Xcode 12.2. The version of the SwiftInfo pod is 2.3.12.

> ./Infofile.swift:2:8: error: module compiled with Swift 5.3 cannot be imported by the Swift 5.3.1 compiler: ************************/iOSApp/Pods/SwiftInfo/bin/../include/swiftinfo/SwiftInfoCore.swiftmodule
> import SwiftInfoCore

I've tried setting the SwiftInfo target `Build Libraries for Distribution` build option to `Yes` as discussed [here](https://stackoverflow.com/a/58656323) but that did not solve the issue.

**Comment by rockbruno** [comment]
Yeah, the module stability thing is a big question mark for me as well. I think the only option is to generate a new version with Xcode 12.2.

In the rake script that generates the binary I delete a bunch of unrelated files, that could also be why the setting doesn't work.

**Comment by rockbruno** [comment]
Pushed 2.3.13

**Comment by MatthewCallery** [comment]
Thanks! 💯
